data <- read.table("~/Nakano_RNAseq/network_analysis/base/GO/CY15_12h_top5GO.txt", sep = "\t", header = T, stringsAsFactors = F)
library(ggplot2)
g <- ggplot(data, aes(x = reorder(GO, log2_FDR), y = log2_FDR))
g <- g + geom_bar(stat = "identity")
g <- g + coord_flip()
g <- g + ylab("")
g <- g + xlab("")
g <- g + theme(axis.text=element_text(size=20), axis.title=element_text(size=20,face="bold"))
g <- g + theme_bw(base_size = 20)
print(g)
ggsave(file = "~/Nakano_RNAseq/network_analysis/results_Fig/tGRN_analysis/tGRN_GO/CY15/CY15_12h_GO.png", plot = g, width = 10, height = 5)
